version: '3.3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: production
      DATABASE_URL: "mysql://root:sshcyber@mysql5:3306/sshcyber"
    networks:
      - mysql-db

networks:
  mysql-db:
    external:
      name: mysql-db