#!/bin/sh

# Set these paths appropriately

BIN=/Users/jayrsawal/GitHub/OpenSSH-Doc-Analyzer/treetagger/bin
CMD=/Users/jayrsawal/GitHub/OpenSSH-Doc-Analyzer/treetagger/cmd
LIB=/Users/jayrsawal/GitHub/OpenSSH-Doc-Analyzer/treetagger/lib

OPTIONS="-token -lemma -sgml"

TAGGER=${BIN}/tree-tagger
TOKENIZER=${CMD}/utf8-tokenize.perl
PARFILE=${LIB}/slovak-utf8.par

$TOKENIZER $* |
$TAGGER $OPTIONS $PARFILE
