#!/bin/sh

# Set these paths appropriately

BIN=/Users/jayrsawal/GitHub/OpenSSH-Doc-Analyzer/treetagger/bin
CMD=/Users/jayrsawal/GitHub/OpenSSH-Doc-Analyzer/treetagger/cmd
LIB=/Users/jayrsawal/GitHub/OpenSSH-Doc-Analyzer/treetagger/lib

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
TAGGER=${BIN}/tree-tagger
TAGGER=tree-tagger
ABBR_LIST=${LIB}/portuguese-abbreviations-utf8
PARFILE=${LIB}/portuguese2-utf8.par

$TOKENIZER -p -a $ABBR_LIST $* |
$TAGGER $OPTIONS $PARFILE
